import Head from 'next/head';
import Nav from '../nav/Nav';
import styles from './Layout.module.css';

const Layout = ({ children }) => {
  return (
    <div className={styles.Layout}>
      <Head>
        <title>Next - Playground App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>
        {children}
      </main>
    </div>
  );
};

export default Layout;
